# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b42856904896a0d94dd76a1a6abaebbbab9806a1ad71270858c62f1677bcb8dfd8d6092088b639e5e3b7049eace0889f9986fb670c46723a21a6c0272cc26e0

test:
  secret_key_base: 22dca24a6a4b4113871e4386a2dba21c4a5d765d44ac9ea423eb1488a772f369176a54a93b0b2e6defff31e572d11c9594667c0440df5842244c08b14cab3db1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
